kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: copter-goodguy
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      
      location / {
        default_type application/json;
        return 200 "Copter Good Guy is Here!";
      }
    }
