kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ping-girls-hunter
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        return 200 "Ping 'The Girls Hunter'"
      }
    }
